### ISSUE TITLE
Project Layout

### ISSUE THREAD

**Issue by thisisagithubaccounta** [blackmathx/scientific-java-library#10]
I'd like to propose a new layout for the project. Inside java would be multiple packages, based on the mathematical topic(Or other topics if applicable) This should help to prevent the project becoming one package full of classes. Some packages that could be used are:

- Algebra
- Calculus
- Discrete
- Geometry
- Probability
- Statistics (could be in same package as probability)

Also a general question about the project, what type of code do you favour. Easy to read or better performance?  Personally I see this being used as an external library for other projects so would favour performance.

**Comment by blackmathx** [comment]
Can you give examples of new classes that would fit in this structure you're proposing?

**Comment by thisisagithubaccounta** [comment]
Sure
- Algebra - Sequences, Series, Quadratics, Linear, Rational, Polynomial
- Calculus - Limits, Integral, Differential
- Discrete - Matrix, Graph, Set
- Geometry - Point, Line, Plane, Angle,
- Statistics - Averages, PValues, Probability

These are just some ideas and wouldn't all have to be implemented at once and could be added upon etc.

**Comment by blackmathx** [comment]
When do you want to do it?

**Comment by thisisagithubaccounta** [comment]
At some point before the first publish on maven. It could be done at the minute with just two packages: Statistics and Algebra.

**Comment by blackmathx** [comment]
I would like to keep this open for a while this project is developed.

**Comment by bowebgit** [comment]
No homo.

**Comment by bowebgit** [comment]
Not needed.

**Comment by boweblogic** [comment]
please consider it.

**Comment by blackmathx** [comment]
Updated the project layout. Complete.

**Comment by blackmathx** [comment]
completed.
