### ISSUE TITLE
Vector Class

### ISSUE THREAD

**Issue by thisisagithubaccounta** [blackmathx/scientific-java-library#11]
A couple of questions regarding the vector class. (I'm basing this off the comments currently in the class)

- What will the copy method do, is this not just the same as Object.clone()
- Is cross the cross product?
- Could i suggest opposite becomes inverse?
- What would getDimension do?

I think this class could grow quite a bit in the future, it could be quite neat. 😃

**Comment by blackmathx** [comment]
Yes it could grow a bit in the future
1. Copy is the same as clone().
2. Cross is the cross product.
3. Inverse is fine with me.
4. getDimension returns the size/length of the vector.

**Comment by blackmathx** [comment]
Closed
